spring:
  data:
    mongodb:
      # mongodb://用户名:密码@IP地址:27017/数据库
      #uri: mongodb://mason:123456@192.168.108.60:27017/appdb
       uri: mongodb://localhost:27017/Datatest
      # 可以不用设置数据库
      #database: Datatest
  datasource:
    url: jdbc:oracle:thin:@//localhost:9805/servicename
    username: username
    password: 123456
    driver-class-name: oracle.jdbc.driver.OracleDriver
    maxWait: 10000
    initial-size: 10
    max-active: 30
    min-idle: 10
mybatis:
  mapper-locations: classpath:mapper/*.xml


